### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by danielefongo** [rainvg/website#1]
- [ ] Fix the nav-bar menu resize bug.
- [ ] Fix the wrong text start in some sections for some window dimensions.
- [ ] (maybe) Try to don't overlap the nav-bar and the sections after clicking an internal-link.
- [ ] Insert every couple (section; topic) in a specific folder.
